import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Sidebar } from './components/sidebar'

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function shouldShowSidebar(pathname: string) {
  const sidebarRoutes = [
    "/dashboard",
    "/appointments",
    "/profile",
    "/settings",
  ];
  // Only show sidebar if pathname matches one of the sidebar routes and is not "/"
  return pathname !== "/" && sidebarRoutes.some((route) => pathname.startsWith(route));
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let pathname = "";
  if (typeof window !== "undefined") {
    pathname = window.location.pathname;
  }
  const showSidebar = shouldShowSidebar(pathname);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {showSidebar && <Sidebar />}
        {children}
      </body>
    </html>
  );
}
